# Generated by Django 3.0.4 on 2020-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherPhone', models.CharField(max_length=10)),
                ('teacherEmailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
